spring:
  # datasource
  datasource:

    url: jdbc:mysql://bj-cynosdbmysql-grp-2ny5n7eg.sql.tencentcdb.com:21436/CugbAcm_Profile?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: thesunspot
    password: Yzzsgqcsdhz1
    driver-class-name: com.mysql.cj.jdbc.Driver
  # thymeleaf模版
  thymeleaf:
    cache: false #关闭缓存

# mybatis
mybatis:
  #mapper-locations: classpath:mapper/*Mapper.xml #mapper目录，如果包是同级的就不需要修改
  type-aliases-package: com.example.cugbacmpractice.bean #别名扫描
  # config-location: #mybatis的核心配置文件，这里暂时没用 QAQ
  configuration:
    map-underscore-to-camel-case: true
#log
logging:
  level:
    com.cugbers.cugbseckill.mapper: debug

